export const actionTypes = {
  CHANGE_EMAIL: "CHANGE_EMAIL",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_INPUT: "CHANGE_INPUT",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_TODOLIST: "UPDATE_TODOLIST",
  IS_LOADING: "IS_LOADING",
  IS_ERROR: "IS_ERROR",
  LOADING_COUNT: "LOADING_COUNT",
};
